---
platform: linux

image: docker:///java#8

inputs:
  - name: sample-spring-cloud-svc-repo
  - name: version

outputs:
  - name: build

run:
  path: sample-spring-cloud-svc-repo/ci/tasks/build-artifact.sh
