---
platform: linux

image: docker:///datianshi/cf-cli

inputs:
  - name: sample-spring-cloud-svc-repo
  - name: sample-spring-cloud-svc-release

run:
  path: sample-spring-cloud-svc-repo/ci/tasks/cf-deployment.sh

params:
  API_ENDPOINT:
  USERNAME:
  PASSWORD:
  ORG:
  SPACE:
  HOST:
